#!/usr/bin/env bash
# Transfers a file from client to server
# Accepts 4 params:
#The path to the file to be transferred
#The IP of the server we want to transfer the file to
#The username scp connects with
#The path to the SSH private key that scp uses
# if less than 3 params passed, displays usage.

if [ "$#" -lt 4 ]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
