#!/uar/bin/env bash
# This script diplays the content of the file etc/passwd
# It only displays username, Id, and home dr path of the user

myfile="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
