#!/usr/bin/env bash
# Echoes Best School 10 times, but the 9th time displays 'Hi' on the line after itself

i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
