#!/usr/bin/env bash
# Configures an Ubuntu server in a specific way as seen below

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhosst" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
